name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set to false to test all configurations
      fail-fast: false

      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        build_type: [Release]
        include:
          - os: windows-latest
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: macos-latest
            cpp_compiler: g++

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache build outputs
      uses: actions/cache@v4
      with:
        path: |
          build
        key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
            ${{ runner.os }}-build-

    - name: Setup MSVC
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Set Build Output Directory
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DFORCE_TESTS=ON
          -G "Visual Studio 17 2022" -A x64
          -S ${{ github.workspace }} 
    
    - name: Configure CMake (Unix)
      if: matrix.os != 'windows-latest'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DFORCE_TESTS=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Generate Test Data
      run: python ${{ github.workspace }}/tests/generate_test_data.py
      working-directory: ${{ github.workspace }}

    - name: Test          
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure --verbose
      working-directory: ${{ steps.strings.outputs.build-output-dir }}

    - name: Prepare Linux package
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p palloc-linux/bin palloc-linux/lib
        cp ${{ steps.strings.outputs.build-output-dir }}/palloc palloc-linux/bin/
        # Copy OR-Tools libraries to lib directory
        cp -L ${{ steps.strings.outputs.build-output-dir }}/or-tools/lib/libortools*.so* palloc-linux/lib/

        # Fix links in the copied libraries
        for lib in palloc-linux/lib/libortools*.so*; do
          if [ -L "$lib" ]; then
            target=$(readlink "$lib")
            target_dir=$(dirname "$target")
            target_name=$(basename "$target")
            new_target="../lib/$target_name"
            ln -sf "$new_target" "$lib"
          fi
        done


    - name: Upload Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: palloc-win
        path: palloc-win/
        if-no-files-found: error

    - name: Upload Linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: palloc-linux
        path: palloc-linux/
        if-no-files-found: error
    
    - name: Upload macOS
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: palloc-macos
        path: palloc-macos/
        if-no-files-found: error
